name: Maven CI/CD

on:
  release:
    types: [created]

jobs:
  publish_release_to_nexus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - uses: s4u/maven-settings-action@v2.4.1
        with:
          servers: |
              [{
                "id": "openzaakbrugextensions-nexus",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
              }]
             
      - name: Publish to Nexus
        run: mvn --batch-mode deploy --file pom.xml
